# See https://cloud.google.com/cloud-build/docs/build-config

# TODO: check
timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE

steps:
  - name: "docker:19.03"
    entrypoint: make
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - VERSION=$_GIT_TAG
      - PULL_BASE_REF=$_PULL_BASE_REF
    args:
      - release.test